#!/bin/bash

# run_micro_project uses the AWS CLI to create a cloudformation stack for a simple web server that produces a static web page
#    The run_micro_project script accepts one OPTIONAL parameter ($1) the STACKNAME default STACKNAME is Stelligent
#
STACKNAME=${1-Stelligent}

# Require the aws cli be installed
AWS=$(which aws)
if [ -z "$AWS" ]
then
  echo "Error: AWS CLI must be installed for $0 to run, please see: http://docs.aws.amazon.com/cli/latest/userguide/installing.html"
  exit
fi

aws cloudformation create-stack --stack-name "$STACKNAME" --template-body file://.//template.json

